name: Deploy
on: 
  push:
    branches: 
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/nosp/git/java/iswebapi
          git fetch && git checkout origin/master
          mvn clean package
