name: Build
on: 
  push:
    branches: 
      - master
jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - name: package
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/nosp/git/iswebapi
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_fozzy_key
          git fetch && git checkout origin/master
          mvn clean package
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: nosp.top
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: echo nosp | sudo -S systemctl restart iswebapi
